"""soft-delete businesses

Revision ID: 800b1fb18d9d
Revises: d71eaaab881f
Create Date: 2026-08-21 12:24:55.827394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800b1fb18d9d'
down_revision: Union[str, None] = 'd71eaaab881f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'deleted_at')
    # ### end Alembic commands ###
